// @ts-check

// 此文件在Node.js环境运行 - 不要使用客户端代码（如浏览器API、JSX等）

/**
 * 创建侧边栏可让你：
 *  - 创建有序的文档组
 *  - 为每个文档组渲染侧边栏
 *  - 提供上/下一篇导航功能
 * 
 * 侧边栏可以从文件系统自动生成，或在此处显式定义。
 * 可以根据需要创建任意数量的侧边栏。
 * 
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // 主站侧边栏 - 自动生成，从docs/主站目录读取
  mainSiteSidebar: [{type: 'autogenerated', dirName: '主站'}],
// 竹节云侧边栏 - 自动生成，从docs/主站目录读取
  zhujieyun: [{type: 'autogenerated', dirName: 'idc'}],
  // MC服务器侧边栏 - 自动生成，从docs/MC目录读取
  mcSidebar: [{type: 'autogenerated', dirName: 'MC'}],
};

export default sidebars;
